### ISSUE TITLE
Provide plugin based on SOBJ-Definition

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit-Plugins#2]
The SAPLink-plugin available  is cumbersome:
- Installation
- licensing

Provide an implementation based on zcl_abapgit_object with does the same job

**Comment by mrsimpson** [comment]
I'd assign myself, if only I could ;) 
@larshp Would you mind pinging me on github[at] beimir[dot]net so that we could discuss how to proceed with respect to development process, contributions, conventions etc?

**Comment by larshp** [comment]
Sent you an email

And I've added you as a collaborator in this repository, so you should be able to assign yourself now. Plus you have direct commit/push access :smile:

**Comment by mrsimpson** [comment]
completed with https://github.com/larshp/abapGit-Plugins/commit/0223ad3bfebb601bd659f568d09cee293bf3ea4c
Extensive Unittest will work only in BOPF-enabled systems (ECC 6.0 >= SP06 or NW 7.50).
- Create a temporary business object model
- Create an instance of this BO
- Export model

However, could not test the plugin itself but "only" the bridge performing the actual work. Reason: Mocking of file-object / injection of XML difficult in `zif_abapgit_object`
