### ISSUE TITLE
Outdated description in readme

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit-Plugins#20]
![image](https://user-images.githubusercontent.com/17437789/34875651-7b933afa-f79e-11e7-8d17-b53ff91478d2.png)

I think this is no longer the case. Should we change it?

**Comment by larshp** [comment]
I think most of abapGit-Plugins is obsolete, so perhaps add that in the description. It supports BOPF, but we should add the important objects in the main abapGit repo instead

**Comment by larshp** [comment]
updated, dont think the saplink bridge is relevant or works any more
