### ISSUE TITLE
Syntax error in ABAPGit Plugin

### ISSUE THREAD

**Issue by A141117** [larshp/abapGit-Plugins#23]
We cloned ABAPGit Plugins repository from Github to SAP system ITX and got syntax error in the plugin classes “Type "ZIF_ABAPGIT_DEFINITIONS" is unknown “. Refer attached docume
[ABAPGit Plugin Issue.docx](https://github.com/larshp/abapGit-Plugins/files/1730306/ABAPGit.Plugin.Issue.docx)
nt.

**Comment by larshp** [comment]
closing, moved to https://github.com/larshp/abapGit/issues/1207

**Comment by A141117** [comment]
Its resolved. Thanks
