### ISSUE TITLE
Issue with abapgit_plugins

### ISSUE THREAD

**Issue by A141117** [larshp/abapGit-Plugins#24]
Hi,

I was trying to upgrade the ZABAPGIT code but after the code copy when i exceute the transaction its giving dump as shown below:
![image](https://user-images.githubusercontent.com/36180668/37072832-883a38c8-2217-11e8-916e-933d52bb669f.png)

The code section (highlighted line no 12048) where it dumps is shown below:
![image](https://user-images.githubusercontent.com/36180668/37072886-b6859880-2217-11e8-947f-843f088a597b.png)

When i checked the abapgit_plugins package then found below issues:
![image](https://user-images.githubusercontent.com/36180668/37072767-338c1670-2217-11e8-9082-558d58203308.png)

**Comment by larshp** [comment]
install the abapGit development version, see http://docs.abapgit.org/guide-upgrade.html 

either via online project or via offline zip file

**Comment by A141117** [comment]
Yes. I did the same. Copied the program from the given notepad and tried to execute so its giving dump.
Previously the package was ZABAPGIT so I saved it in same as it is not allowing me to create in $ABAPGIT package. Please help.

**Comment by A141117** [comment]
I did same upgrade in ISU system and it worked well. Now I'm trying to do same stuff this in CRM system and facing issue. I think some inconsistency happened. How can i do this tool from scratch?

**Comment by A141117** [comment]
@larshp I tried to uninstall and start again from scratch and copied the code from there. Still getting a dump on same code lines.

**Comment by larshp** [comment]
try deleting all objects in package ZABAPGIT_PLUGIN, and then install clean version of abapGit

**Comment by A141117** [comment]
Yes i did the same. Uninstalled and deleted object. However, the dump was still coming and i could not go to the abapgit main screen. So I temporarily commented the code piece because of which the dump was coming. Then I could execute the program and see the main screen. Afterwards, I uninstalled everything and did it scratch. Now it works fine. Thanks @larshp for quick responses.

**Comment by larshp** [comment]
Okay, I'm not quite sure what happened, but I guess e can close the issue?

**Comment by A141117** [comment]
Yes, we can close this issue.
