### ISSUE TITLE
DBSQL_DUPLICATE_KEY_ERROR when importing IWPR (SAP Gateway Builder Project)

### ISSUE THREAD

**Issue by gregorwolf** [larshp/abapGit-Plugins#25]
I've used the abapGit-Plugins to export a SAP Gateway Builder Project (Transaction SEGW) to a Git Repository from a NetWeaver 7.40 system. When importing in a NetWeaver 7.52 system a dump was created with DBSQL_DUPLICATE_KEY_ERROR when trying to insert in table /IWBEP/I_SBD_MAP. I've checked the content of lt_imported_table_content in method import_object of lcl_tlogo_bridge and found that the line for table /IWBEP/I_SBD_MAP was initial. So it seems that the assignment that is checked to contain lines is from the last loop.

**Comment by larshp** [comment]
closing, guess this was fixed in https://github.com/larshp/abapGit-Plugins/commit/c1ccf0b103ad130d7e2cc07374332a74c7d207a7

plus IWPR is now supported natively(without the plugins) in abapGit
