### ISSUE TITLE
Ordering Issues for BW Objects

### ISSUE THREAD

**Issue by timostark** [larshp/abapGit-Plugins#29]
Hi All,

When using the ABAP-Git Plugin massively for BW objects, occasionally there are change-detection issues. What happens is that i commit a change, but after a refresh i get the same object i just commited again marked as changed - The reason is a different order of the table entries in the serialized XML.

The root cause seems to be very simple.. In `ZCL_ABAPGITP_OBJECT_BY_SOBJ `- local class `lcl_tlogo_bridge`, method `GET_CURRENT_TABLE_CONTENT`, you are generically selecting the OBJP tables without `ORDER BY` statement.
![image](https://user-images.githubusercontent.com/19237828/57937659-aa728380-78c6-11e9-805a-b09642bf20be.png)

I haven't debugged it until the end, but certainly an inconsistent sort order (of e.g. SAP HANA) can lead to a different order of the XML at the end. A simple `ORDER BY PRIMARY KEY` seems to solve the issue in a few tests.
![image](https://user-images.githubusercontent.com/19237828/57937768-edccf200-78c6-11e9-9bee-3e943f349e34.png)

Question: i can of course raise a pull request for this - but as the last commit is already 5 months old, i am not sure if this project is still under maintenance (especially rgd. the obsolete warning) --> _Do you still accept PRs?_

Thanks,
Timo

PS: As a more general question - Copying the serialized table content will probably work (as long as there is no remodeling, or similar stuff) - Still of course it is pretty "hacked". Have you seen any project using ABAPGit for BW objects (BW 750 or BW4HANA)?

**Comment by larshp** [comment]
yes, pull requests welcome

however the overall plan is to move everything from this plugins project into the main abapgit code by using https://github.com/larshp/abapGit/blob/master/src/objects/zcl_abapgit_objects_generic.clas.abap, this makes it easier to maintain

BW: no, I typically only do ABAP stuff

**Comment by larshp** [comment]
you are also welcome to submit a generic serializer for the objects needed to the main abapGit repo, see example in https://github.com/larshp/abapGit/blob/master/src/objects/zcl_abapgit_object_asfc.clas.abap

**Comment by larshp** [comment]
Core abapGit fix: https://github.com/larshp/abapGit/pull/2713
