### ISSUE TITLE
Object type SUCU not supported, serialize

### ISSUE THREAD

**Issue by wenbof-zx** [larshp/abapGit-Plugins#35]
![abapgitinstallerror](https://user-images.githubusercontent.com/61670890/79337004-4f726200-7f57-11ea-9731-d15e0f62bc40.JPG)

I have installed ABAP-Git from https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap

Now I can see both the ZABAPGIT_FULL and ZABAPGIT programs in the system. could you please help provide the latest plugin link so that I can apply the latest patch? thanks.

**Comment by larshp** [comment]
from the readme, 

> These plugins will sometime become obsolete, see https://github.com/larshp/abapGit/issues/1449 and https://github.com/larshp/abapGit/pull/1590

SUCU is now part of the officially supported object types, https://docs.abapgit.org/ref-supported.html, so no need to use abapGit-Plugins for it anymore

**Comment by wenbof-zx** [comment]
Thanks. I installed it via steps following "Copy the ABAP code(right click -> save-as) into a new report named i.e. ZABAPGIT_FULL via SE38 or SE80". would you like me to install it again?
It seems I only tried to add one called ZABAPGIT_FULL while the ZABAPGIT came automatically.

**Comment by larshp** [comment]
I tried installing https://github.com/abapGit-tests/SUCU with the latest version, no issues

can you reproduce the issue with some dummy data in a public repository?

**Comment by wenbof-zx** [comment]
Figured it out. we can close this one. thanks very much for your prompt reply.

**Comment by larshp** [comment]
can you help adding a description of the solution? to help others in case they run into the same problem
