### ISSUE TITLE
Caution: "After Import" logic is not standard

### ISSUE THREAD

**Issue by mbtools** [larshp/abapGit-Plugins#36]
Just a word of caution...

The SOBJ handler calls the after import method separately for each object. A standard transport calls the after import method once per transport and includes all objects. 

Therefore, the standard transport will handle with dependencies between objects by for example, executing the after import methods in a specific order (as defined by data element RSTLOGO). This will not happen in abapGit.

**Comment by larshp** [comment]
suggest writing custom serializers for the object types needed, instead of using these plugins
