### ISSUE TITLE
Generic plugin does not remove TADIR-entry

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit-Plugins#8]
- Create BOPF object
- use uninstall option
  => BOPF object gone, TADIR remains

**Comment by larshp** [comment]
see similar issue https://github.com/larshp/abapGit/issues/114 and proposed solution

**Comment by larshp** [comment]
looks like this is actually implemented
https://github.com/larshp/abapGit-Plugins/blob/0aa743e2c46b66bbda3d7c14e52318dc06278a63/zcl_abapgit_object_by_sobj.clas.abap#L82

now that https://github.com/larshp/abapGit/issues/114 is closed it is also possible to set `delete_tadir` in the metadata, and abapGit will handle the deletion

but I guess the current implementation is also okay? @mrsimpson

**Comment by mrsimpson** [comment]
Even if it was implemented properly (which I doubt), I'd favor to use an option offered by the enclosing framework, if that exists. Need to get my system up and running, so it seems...

**Comment by larshp** [comment]
fixed, see above commit

**Comment by larshp** [comment]
fixed, see previous comments, set

`rs_metadata-delete_tadir = abap_true.`
